# Generated by Django 4.0.3 on 2023-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airportCode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airportName', models.CharField(max_length=255)),
            ],
        ),
    ]
